// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdQlwQ1Q8iUP7ttpgaJ7fkV8yt5-aZEd8',
    appId: '1:72672407667:web:00dbc032ce71d8bddfba06',
    messagingSenderId: '72672407667',
    projectId: 'hackathon-92e0f',
    authDomain: 'hackathon-92e0f.firebaseapp.com',
    storageBucket: 'hackathon-92e0f.firebasestorage.app',
    measurementId: 'G-8LZ68C5F8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBusmzEYVdlFjsLFFeIKBFr0aK6cHsjsg8',
    appId: '1:72672407667:android:92584775453e49c7dfba06',
    messagingSenderId: '72672407667',
    projectId: 'hackathon-92e0f',
    storageBucket: 'hackathon-92e0f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FMZO7F9gmqHZwx59qDV8PnLAAsBB-kE',
    appId: '1:72672407667:ios:468f7d4c4df02dafdfba06',
    messagingSenderId: '72672407667',
    projectId: 'hackathon-92e0f',
    storageBucket: 'hackathon-92e0f.firebasestorage.app',
    iosClientId: '72672407667-2sqs41oqmijpfn814gsfss1cl3du6crb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3FMZO7F9gmqHZwx59qDV8PnLAAsBB-kE',
    appId: '1:72672407667:ios:468f7d4c4df02dafdfba06',
    messagingSenderId: '72672407667',
    projectId: 'hackathon-92e0f',
    storageBucket: 'hackathon-92e0f.firebasestorage.app',
    iosClientId: '72672407667-2sqs41oqmijpfn814gsfss1cl3du6crb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdQlwQ1Q8iUP7ttpgaJ7fkV8yt5-aZEd8',
    appId: '1:72672407667:web:00dbc032ce71d8bddfba06',
    messagingSenderId: '72672407667',
    projectId: 'hackathon-92e0f',
    authDomain: 'hackathon-92e0f.firebaseapp.com',
    storageBucket: 'hackathon-92e0f.firebasestorage.app',
    measurementId: 'G-8LZ68C5F8V',
  );
}
